# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Mesage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя:')),
                ('email', models.EmailField(max_length=254, verbose_name='Почт. ящик:')),
                ('website', models.URLField(verbose_name='Сайт:')),
                ('text', models.TextField(verbose_name='Сообщение:')),
            ],
            options={
                'verbose_name_plural': 'Сообщения',
                'verbose_name': 'Сообщение',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название:')),
                ('description', models.TextField(verbose_name='Описание:')),
                ('img_small', models.ImageField(upload_to='portfolio/%d-%m-%Y', verbose_name='Мал. изображение:')),
                ('img_big', models.ImageField(upload_to='portfolio/%d-%m-%Y', verbose_name='Бол. изображение:')),
                ('project_url', models.URLField(verbose_name='Ссылка проекта:')),
                ('download', models.URLField(max_length=300, verbose_name='Ссылка скачки:')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания:')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации:')),
                ('likes', models.IntegerField(default=0, verbose_name='Кол. лайков:')),
                ('previews', models.IntegerField(default=0, verbose_name='Кол. просмотров:')),
                ('category', models.ManyToManyField(to='my_site.Category', verbose_name='Категория(и):')),
            ],
            options={
                'verbose_name_plural': 'Работы',
                'verbose_name': 'Работа',
            },
        ),
    ]
