# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesage',
            name='website',
        ),
        migrations.AlterField(
            model_name='mesage',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя:'),
        ),
    ]
